import bcrypt from 'bcryptjs';
import { query } from './index';
import { DATABASE_LISTING_ASSETS } from '../utils/canonicalProducts';

export async function seedDiverseMarketplace() {
  console.log('[Seed] Starting comprehensive realistic specialized marketplace population into PostgreSQL...');

  const defaultHash = await bcrypt.hash('FarmPass@2026', 10);
  const defaultPinHash = await bcrypt.hash('2026', 10);

  // 1. 14 Distinct Regional Farmers Across India
  const farmers = [
    {
      userId: 'usr-ravi-kumar',
      farmerId: 'AV-FARM-1001',
      name: 'Ravi Kumar',
      email: 'ravi.kumar@auricvista.farm',
      role: 'farmer',
      phone: '+91 98450 12890',
      location: 'Chikkaballapur, Karnataka',
      farmName: 'Kumar Organic Red Soil Farm',
      farmerSlug: 'ravi-kumar',
      mainCrops: 'Heirloom Vine Tomatoes, Baby Spinach, Golden Carrots, Sweet Kaddu',
      experience: '18 years',
      specialty: 'Organic Vegetables & Native Roots',
      acreage: '14 Acres Certified Natural',
      highlightBadge: 'Master Grower',
      description: 'Pioneer of chemical-free heirloom vegetable cultivation in the fertile red loam soil of Chikkaballapur.',
    },
    {
      userId: 'usr-lakshmi-devi',
      farmerId: 'AV-FARM-1002',
      name: 'Lakshmi Devi',
      email: 'lakshmi.devi@auricvista.farm',
      role: 'farmer',
      phone: '+91 94480 34120',
      location: 'Kolar, Karnataka',
      farmName: 'Devi Hydroponic & Exotic Fruit Orchards',
      farmerSlug: 'lakshmi-devi',
      mainCrops: 'Hydroponic Greens, Red Lady Papaya, Muskmelon',
      experience: '12 years',
      specialty: 'Hydroponic Greens & Exotic Melons',
      acreage: '8 Acres Precision Soil',
      highlightBadge: 'Zero Pesticide Pioneer',
      description: 'Specializes in nutrient-rich cold-water hydroponics and naturally ripened table fruits.',
    },
    {
      userId: 'usr-suresh-naidu',
      farmerId: 'AV-FARM-1003',
      name: 'Suresh Naidu',
      email: 'suresh.naidu@auricvista.farm',
      role: 'farmer',
      phone: '+91 98860 78234',
      location: 'Hosur Agro Ridge, Tamil Nadu',
      farmName: 'Naidu Ancestral Millet & Pulse Reserve',
      farmerSlug: 'suresh-naidu',
      mainCrops: 'Finger Millet (Ragi), Desi Toor Dal, Country Gourds',
      experience: '22 years',
      specialty: 'Heritage Millets, Pulses & Native Grains',
      acreage: '26 Acres Ancestral Farm',
      highlightBadge: 'Heritage Cultivator',
      description: 'Preserves native drought-resistant millet seeds and unpolished heirloom lentils without synthetic chemicals.',
    },
    {
      userId: 'usr-nitin-patil',
      farmerId: 'AV-FARM-1004',
      name: 'Nitin Patil',
      email: 'nitin.patil@auricvista.farm',
      role: 'farmer',
      phone: '+91 98220 54321',
      location: 'Ratnagiri & Mahabaleshwar, Maharashtra',
      farmName: 'Patil Konkan Coast Agro Orchards',
      farmerSlug: 'nitin-patil',
      mainCrops: 'Ratnagiri Alphonso Mangoes, Dahanu Sapota, Strawberries',
      experience: '25 years',
      specialty: 'GI-Tagged Alphonso Mangoes & Coastal Berries',
      acreage: '30 Acres Coastal Laterite Soil',
      highlightBadge: 'GI Tagged Specialist',
      description: 'Award-winning Alphonso grower adhering strictly to tree-ripened, calcium-carbide-free harvesting.',
    },
    {
      userId: 'usr-balwinder-singh',
      farmerId: 'AV-FARM-1005',
      name: 'Balwinder Singh',
      email: 'balwinder.singh@auricvista.farm',
      role: 'farmer',
      phone: '+91 98140 67890',
      location: 'Ludhiana, Punjab',
      farmName: 'Singh Golden Fields Grain Farm',
      farmerSlug: 'balwinder-singh',
      mainCrops: 'Sharbati Golden Wheat, Basmati Rice, Mustard, White Radish',
      experience: '30 years',
      specialty: 'Organic Golden Wheat & Long-Grain Grains',
      acreage: '45 Acres Alluvial Soil',
      highlightBadge: 'Grain Champion',
      description: 'Dedicated to soil microbiology restoration and non-GMO high-protein wheat and aromatic long-grain paddy.',
    },
    {
      userId: 'usr-kavita-patel',
      farmerId: 'AV-FARM-1006',
      name: 'Kavita Patel',
      email: 'kavita.patel@auricvista.farm',
      role: 'farmer',
      phone: '+91 98790 12345',
      location: 'Unjha & Junagadh, Gujarat',
      farmName: 'Patel Natural Spice & Cold-Press Mill',
      farmerSlug: 'kavita-patel',
      mainCrops: 'Unjha Cumin (Jeera), Groundnut Oil, Kabuli Chickpeas',
      experience: '15 years',
      specialty: 'Sun-Dried Cumin, Garlic & Cold-Pressed Groundnut Oil',
      acreage: '18 Acres Saurashtra Black Soil',
      highlightBadge: 'Spice Guild Master',
      description: 'Produces export-quality unadulterated essential spices and single-origin wood-pressed edible oils.',
    },
    {
      userId: 'usr-mathew-joseph',
      farmerId: 'AV-FARM-1007',
      name: 'Mathew Joseph',
      email: 'mathew.joseph@auricvista.farm',
      role: 'farmer',
      phone: '+91 94470 98765',
      location: 'Wayanad & Idukki, Kerala',
      farmName: 'Highland Mist Spice & Rainforest Plantation',
      farmerSlug: 'mathew-joseph',
      mainCrops: 'Tellicherry Black Pepper, Green Cardamom, Fresh Ginger, Pineapples',
      experience: '20 years',
      specialty: 'High-Altitude Spices & Virgin Coconut Oil',
      acreage: '22 Acres High Range Agro-Forest',
      highlightBadge: 'Rainforest Certified',
      description: 'Cultivates biodiversity-shaded spices in the misty Western Ghats under strict organic permaculture.',
    },
    {
      userId: 'usr-rameshwar-lal',
      farmerId: 'AV-FARM-1008',
      name: 'Rameshwar Lal',
      email: 'rameshwar.lal@auricvista.farm',
      role: 'farmer',
      phone: '+91 94140 45678',
      location: 'Nagaur & Jodhpur, Rajasthan',
      farmName: 'Marwar Desert Bloom Agro Farm',
      farmerSlug: 'rameshwar-lal',
      mainCrops: 'Whole Dhaniya Seeds, Organic Methi Dana, Desert Bajra',
      experience: '28 years',
      specialty: 'Aromatic Coriander, Methi & Desert Pulses',
      acreage: '35 Acres Arid Organic Soil',
      highlightBadge: 'Desert Farming Hero',
      description: 'Harnesses traditional water harvesting to grow intensely fragrant desert spices and drought-hardy millets.',
    },
    {
      userId: 'usr-venkatesh-rao',
      farmerId: 'AV-FARM-1009',
      name: 'Venkatesh Rao',
      email: 'venkatesh.rao@auricvista.farm',
      role: 'farmer',
      phone: '+91 98480 33445',
      location: 'Guntur & Tenali, Andhra Pradesh',
      farmName: 'Krishna Delta Natural Farm',
      farmerSlug: 'venkatesh-rao',
      mainCrops: 'Spicy Green Chillies, Curry Leaves, Black Urad Dal',
      experience: '16 years',
      specialty: 'Direct Farm Chillies, Fresh Curry Leaves & Pulses',
      acreage: '20 Acres Krishna River Basin',
      highlightBadge: 'Delta Harvest Leader',
      description: 'Supplies high-heat chemical-free chillies and fragrant culinary greens nurtured by rich river sediment.',
    },
    {
      userId: 'usr-gurpreet-chahal',
      farmerId: 'AV-FARM-1010',
      name: 'Gurpreet Chahal',
      email: 'gurpreet.chahal@auricvista.farm',
      role: 'farmer',
      phone: '+91 98160 88990',
      location: 'Shimla & Solan, Himachal Pradesh',
      farmName: 'Himalayan Ridge Crisp Fruit Orchards',
      farmerSlug: 'gurpreet-chahal',
      mainCrops: 'Shimla Royal Delicious Apples, Sweet Green Peas, Green Capsicum',
      experience: '19 years',
      specialty: 'High-Altitude Apples & Cold-Climate Vegetables',
      acreage: '16 Acres Mountain Terrace',
      highlightBadge: 'Himalayan Orchardist',
      description: 'Mountain-stream irrigated snow-climate apples and tender winter pods picked at peak sugar content.',
    },
    {
      userId: 'usr-subhash-mondal',
      farmerId: 'AV-FARM-1011',
      name: 'Subhash Mondal',
      email: 'subhash.mondal@auricvista.farm',
      role: 'farmer',
      phone: '+91 98300 22334',
      location: 'Sundarbans, West Bengal',
      farmName: 'Mangrove Fringe Natural Reserve',
      farmerSlug: 'subhash-mondal',
      mainCrops: 'Wild Forest Raw Honey, Heritage Paddy',
      experience: '24 years',
      specialty: 'Ethical Wild Mangrove Honey & Native Rice',
      acreage: '12 Acres Forest Fringe',
      highlightBadge: 'Bio-Heritage Guardian',
      description: 'Harvests unfiltered, unheated wild raw honey directly from mangrove floral blooms in the Sundarbans biosphere.',
    },
    {
      userId: 'usr-arunachalam-murugan',
      farmerId: 'AV-FARM-1012',
      name: 'Arunachalam Murugan',
      email: 'arunachalam.murugan@auricvista.farm',
      role: 'farmer',
      phone: '+91 94430 77889',
      location: 'Pollachi & Coimbatore, Tamil Nadu',
      farmName: 'Anamalai Foothills Coconut & Moringa Estate',
      farmerSlug: 'arunachalam-murugan',
      mainCrops: 'Pollachi Fresh Coconuts, Moringa Drumsticks, Nilgiri Carrots',
      experience: '21 years',
      specialty: 'Nutrient-Dense Coconuts, Moringa & Hill Roots',
      acreage: '28 Acres Foothill Loam',
      highlightBadge: 'Tree-Crop Specialist',
      description: 'Tender sweet coconuts and high-protein moringa pods cultivated with natural composting and drip irrigation.',
    },
    {
      userId: 'usr-pradip-deshmukh',
      farmerId: 'AV-FARM-1013',
      name: 'Pradip Deshmukh',
      email: 'pradip.deshmukh@auricvista.farm',
      role: 'farmer',
      phone: '+91 98230 11223',
      location: 'Nashik & Kolhapur, Maharashtra',
      farmName: 'Sahyadri Valley Vineyard & Sugar Estate',
      farmerSlug: 'pradip-deshmukh',
      mainCrops: 'Nashik Red Onions, Seedless Table Grapes, Kolhapur Jaggery',
      experience: '26 years',
      specialty: 'Storage Onions, Table Grapes & Artisanal Jaggery',
      acreage: '32 Acres Sahyadri Foothill',
      highlightBadge: 'Agri-Processing Leader',
      description: 'Known for high-dry-matter storage onions, sweet table grapes, and preservative-free solid sugarcane jaggery.',
    },
    {
      userId: 'usr-ghulam-mir',
      farmerId: 'AV-FARM-1015',
      name: 'Ghulam Hassan Mir',
      email: 'ghulam.mir@auricvista.farm',
      role: 'farmer',
      phone: '+91 94190 66778',
      location: 'Pampore & Sopore, Jammu & Kashmir',
      farmName: 'Kashmir Valley Saffron & Walnut Heritage',
      farmerSlug: 'ghulam-mir',
      mainCrops: 'Kashmir Kesar Saffron, Snow White Walnut Kernels',
      experience: '35 years',
      specialty: 'GI-Tagged Pampore Saffron & Kashmiri Walnuts',
      acreage: '10 Acres Karewa Soil',
      highlightBadge: 'Heritage Saffron Master',
      description: 'Fourth-generation saffron grower picking purple crocus flowers by hand during the autumn dawn harvest.',
    },
  ];

  for (const f of farmers) {
    await query(
      `INSERT INTO users (id, farmer_id, name, email, password_hash, pin_hash, role, phone, location, farm_name, main_crops)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
       ON CONFLICT (email) DO UPDATE SET 
         password_hash = EXCLUDED.password_hash,
         farmer_id = COALESCE(users.farmer_id, EXCLUDED.farmer_id),
         location = EXCLUDED.location,
         farm_name = EXCLUDED.farm_name,
         main_crops = EXCLUDED.main_crops;`,
      [f.userId, f.farmerId, f.name, f.email, defaultHash, defaultPinHash, f.role, f.phone, f.location, f.farmName, f.mainCrops]
    );

    await query(
      `INSERT INTO farmer_profiles (id, user_id, farmer_slug, farm_name, location, experience, specialty, acreage, highlight_badge, description, verification_status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'verified')
       ON CONFLICT (farmer_slug) DO UPDATE SET
         farm_name = EXCLUDED.farm_name,
         location = EXCLUDED.location,
         specialty = EXCLUDED.specialty,
         acreage = EXCLUDED.acreage,
         highlight_badge = EXCLUDED.highlight_badge,
         description = EXCLUDED.description;`,
      [
        `prof-${f.farmerSlug}`,
        f.userId,
        f.farmerSlug,
        f.farmName,
        f.location,
        f.experience,
        f.specialty,
        f.acreage,
        f.highlightBadge,
        f.description,
      ]
    );
  }

  // 2. Realistic, Geographically & Agriculturally Specialized Produce Listings
  // Each farmer has strictly 5 to 6 relevant products in their domain.
  const diverseListings = [
    // =========================================================================
    // 1. RAVI KUMAR (Chikkaballapur, Karnataka) - Organic Vegetables & Native Roots
    // =========================================================================
    {
      id: 'PROD-RAVI-01',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Farm, Chikkaballapur, Karnataka',
      name: 'Heirloom Vine Tomatoes (Tamatar)',
      category: 'Vegetables',
      quantity: 85,
      unit: 'kg',
      price: 38,
      description: 'Naturally pollinated, open-pollinated heirloom vine tomatoes harvested at dawn in Chikkaballapur red loam. Juicy, rich in lycopene, with balanced sweetness.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAVI-02',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Farm, Chikkaballapur, Karnataka',
      name: 'Mysore Long Purple Brinjal (Baingan)',
      category: 'Vegetables',
      quantity: 55,
      unit: 'kg',
      price: 34,
      description: 'Slender, glossy purple brinjal with tender flesh and minimal seeds. Chemical-free cultivation with natural vermicompost and neem oil protection.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1628773822503-930a84d9f691?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAVI-03',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Farm, Chikkaballapur, Karnataka',
      name: 'Tender Green Okra / Ladies Finger (Bhindi)',
      category: 'Vegetables',
      quantity: 48,
      unit: 'kg',
      price: 42,
      description: 'Hand-snapped young green okra pods, crisp and non-fibrous. Perfect for quick dry roasts and curries with zero pesticide sprays.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1425543103986-22abb7d7e8d2?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAVI-04',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Farm, Chikkaballapur, Karnataka',
      name: 'Crisp Green Country Cucumbers (Kheera)',
      category: 'Vegetables',
      quantity: 65,
      unit: 'kg',
      price: 28,
      description: 'Field-grown crisp country cucumbers with dark green thin skin and refreshing cool water content. Harvested at sunrise for salad freshness.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAVI-05',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Farm, Chikkaballapur, Karnataka',
      name: 'Organic Sweet Pumpkin (Kaddu)',
      category: 'Vegetables',
      quantity: 45,
      unit: 'kg',
      price: 32,
      description: 'Dense, nutrient-dense golden orange pumpkin grown in Chikkaballapur red soil. Naturally sweet with high beta-carotene and excellent shelf life.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1506917728037-b6af01a7d403?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.5,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAVI-06',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Farm, Chikkaballapur, Karnataka',
      name: 'Fragrant Country Coriander Leaves (Dhaniya)',
      category: 'Herbs & Leafy Greens',
      quantity: 60,
      unit: 'bunch',
      price: 15,
      description: 'Intensely aromatic native small-leaf coriander with roots intact. Grown without synthetic fertilizers, offering unmatched culinary flavor.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1592417817098-8f3d69109853?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 2. LAKSHMI DEVI (Kolar, Karnataka) - Hydroponic Greens & Exotic Melons
    // =========================================================================
    {
      id: 'PROD-LAKSHMI-01',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic & Exotic Fruit Orchards, Kolar, Karnataka',
      name: 'Red Lady Honey-Sweet Papaya',
      category: 'Fruits',
      quantity: 70,
      unit: 'kg',
      price: 48,
      description: 'Tree-ripened Red Lady variety papaya featuring thick salmon-red flesh, smooth buttery texture, and high natural papain enzyme.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-LAKSHMI-02',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic & Exotic Fruit Orchards, Kolar, Karnataka',
      name: 'Honey Sweet Muskmelon (Kharbuja)',
      category: 'Fruits',
      quantity: 80,
      unit: 'kg',
      price: 55,
      description: 'Fragrant netted muskmelon with tender salmon pulp and floral honey sweetness. Grown under controlled microclimate drip irrigation.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-LAKSHMI-03',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic & Exotic Fruit Orchards, Kolar, Karnataka',
      name: 'Hydroponic Baby Spinach Leaves (Palak)',
      category: 'Herbs & Leafy Greens',
      quantity: 55,
      unit: 'bunch',
      price: 40,
      description: 'Soil-less nutrient-film hydroponic baby spinach leaves. Zero grit, zero chemical residue, crisp stems with roots hydrated in cold water.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-LAKSHMI-04',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic & Exotic Fruit Orchards, Kolar, Karnataka',
      name: 'Crisp Hydroponic Butterhead Salad Lettuce',
      category: 'Herbs & Leafy Greens',
      quantity: 45,
      unit: 'bunch',
      price: 65,
      description: 'Live-head butterhead lettuce with silky, soft sweet leaves. Grown in RO-mineral circulating water with root balls intact for multi-day freshness.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1556801712-76c8eb07ebb3?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-LAKSHMI-05',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic & Exotic Fruit Orchards, Kolar, Karnataka',
      name: 'Fresh Garden Peppermint (Pudina Leaves)',
      category: 'Herbs & Leafy Greens',
      quantity: 65,
      unit: 'bunch',
      price: 18,
      description: 'High-menthol dark green peppermint sprigs harvested at 5 AM. Potent cooling aroma ideal for fresh chutneys, teas, and summer coolers.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-LAKSHMI-06',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic & Exotic Fruit Orchards, Kolar, Karnataka',
      name: 'Sweet Table Strawberries (Hydroponic)',
      category: 'Fruits',
      quantity: 40,
      unit: 'box',
      price: 130,
      description: 'Greenhouse-cultivated sweet red strawberries picked ripe off hydroponic gutters. Juicy, fragrant, and free of dirt or pesticide residues.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 3. SURESH NAIDU (Hosur Agro Ridge, TN/Karnataka) - Heritage Millets, Pulses & Native Grains
    // =========================================================================
    {
      id: 'PROD-SURESH-01',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Millet Reserve, Hosur Agro Ridge, Tamil Nadu',
      name: 'Mandya Whole Finger Millet (Ragi Whole Grain)',
      category: 'Grains & Cereals',
      quantity: 140,
      unit: 'kg',
      price: 48,
      description: 'Ancient heirloom finger millet seeds harvested from rain-fed drylands. Extremely rich in bioavailable calcium, dietary fiber, and plant iron.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SURESH-02',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Millet Reserve, Hosur Agro Ridge, Tamil Nadu',
      name: 'Native Foxtail Millet (Kangni / Navane Grains)',
      category: 'Grains & Cereals',
      quantity: 90,
      unit: 'kg',
      price: 75,
      description: 'Unpolished golden foxtail millet grains grown with zero chemicals. Low glycemic index grain perfect as a healthy diabetic rice replacement.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SURESH-03',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Millet Reserve, Hosur Agro Ridge, Tamil Nadu',
      name: 'Gulbarga Desi Unpolished Toor Dal (Arhar)',
      category: 'Pulses & Dals',
      quantity: 95,
      unit: 'kg',
      price: 145,
      description: 'Naturally sun-dried split pigeon peas from heritage indigenous seeds. Unpolished, non-oiled, preserving rich yellow pigment and nutty dal aroma.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SURESH-04',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Millet Reserve, Hosur Agro Ridge, Tamil Nadu',
      name: 'Fresh Country Bottle Gourd (Lauki)',
      category: 'Vegetables',
      quantity: 60,
      unit: 'piece',
      price: 30,
      description: 'Tender, straight country bottle gourd with pale green skin and soft spongy seed core. High in alkaline hydration and dietary electrolytes.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.5,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SURESH-05',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Millet Reserve, Hosur Agro Ridge, Tamil Nadu',
      name: 'Organic Tender Ridge Gourd (Turai)',
      category: 'Vegetables',
      quantity: 50,
      unit: 'kg',
      price: 38,
      description: 'Crisp angled ridge gourds picked young from trellised vines. Rich in dietary cellulose and Vitamin C with light, delicate taste.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SURESH-06',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Millet Reserve, Hosur Agro Ridge, Tamil Nadu',
      name: 'Desi Brown Horse Gram (Kulthi Dal)',
      category: 'Pulses & Dals',
      quantity: 75,
      unit: 'kg',
      price: 85,
      description: 'High-protein ancestral horse gram from dryland fields. Renowned in Ayurvedic cooking for metabolism, joint strength, and hearty winter soups.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 4. NITIN PATIL (Ratnagiri & Mahabaleshwar, MH) - GI-Tagged Mangoes & Coastal Berries
    // =========================================================================
    {
      id: 'PROD-NITIN-01',
      farmerId: 'usr-nitin-patil',
      farmerName: 'Nitin Patil',
      farmerEmail: 'nitin.patil@auricvista.farm',
      farmLocation: 'Patil Konkan Coast Agro Orchards, Ratnagiri, Maharashtra',
      name: 'Ratnagiri Alphonso Mangoes (GI Tagged)',
      category: 'Fruits',
      quantity: 120,
      unit: 'dozen',
      price: 650,
      description: 'Naturally tree-ripened, golden-hued export grade Alphonso mangoes with rich saffron aroma and zero artificial ripening chemicals.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-NITIN-02',
      farmerId: 'usr-nitin-patil',
      farmerName: 'Nitin Patil',
      farmerEmail: 'nitin.patil@auricvista.farm',
      farmLocation: 'Patil Konkan Coast Agro Orchards, Ratnagiri, Maharashtra',
      name: 'Dahanu Bordi Sweet Sapota (Chikoo)',
      category: 'Fruits',
      quantity: 85,
      unit: 'kg',
      price: 60,
      description: 'GI-certified Konkan coast sapota with sandy-brown skin and exceptionally sweet, malt-caramel flavored pulp. Calcium-carbide free.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-NITIN-03',
      farmerId: 'usr-nitin-patil',
      farmerName: 'Nitin Patil',
      farmerEmail: 'nitin.patil@auricvista.farm',
      farmLocation: 'Patil Konkan Coast Agro Orchards, Mahabaleshwar, Maharashtra',
      name: 'Mahabaleshwar Fresh Sweet Strawberries',
      category: 'Fruits',
      quantity: 65,
      unit: 'box',
      price: 140,
      description: 'Hill-terrace grown crimson strawberries from Mahabaleshwar mist. Luscious, intensely fragrant, hand-packed in cushioned punnets.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1518635017498-87f514b751ba?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-NITIN-04',
      farmerId: 'usr-nitin-patil',
      farmerName: 'Nitin Patil',
      farmerEmail: 'nitin.patil@auricvista.farm',
      farmLocation: 'Patil Konkan Coast Agro Orchards, Ratnagiri, Maharashtra',
      name: 'Konkan Sun-Dried Red Kokum Rind (Aamsul)',
      category: 'Organic & Natural',
      quantity: 45,
      unit: 'kg',
      price: 220,
      description: 'Pure sun-dried Garcinia indica kokum peels cured with sea salt. Essential souring agent with potent antioxidant hydroxycitric acid (HCA).',
      images: JSON.stringify(['https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-NITIN-05',
      farmerId: 'usr-nitin-patil',
      farmerName: 'Nitin Patil',
      farmerEmail: 'nitin.patil@auricvista.farm',
      farmLocation: 'Patil Konkan Coast Agro Orchards, Ratnagiri, Maharashtra',
      name: 'Allahabad Safeda Crisp White Guava',
      category: 'Fruits',
      quantity: 75,
      unit: 'kg',
      price: 65,
      description: 'Crisp white-fleshed guavas with velvety skin, pleasant musky sweetness, and abundant dietary Vitamin C and natural pectin.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1536511135885-3004a434d284?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 5. BALWINDER SINGH (Ludhiana, Punjab) - Organic Golden Wheat & Long-Grain Grains
    // =========================================================================
    {
      id: 'PROD-BALWINDER-01',
      farmerId: 'usr-balwinder-singh',
      farmerName: 'Balwinder Singh',
      farmerEmail: 'balwinder.singh@auricvista.farm',
      farmLocation: 'Singh Golden Fields Grain Farm, Ludhiana, Punjab',
      name: 'Sehore Sharbati Golden Wheat Grains (Gehu)',
      category: 'Grains & Cereals',
      quantity: 260,
      unit: 'kg',
      price: 55,
      description: 'Heavy golden Sharbati wheat kernels nurtured by alluvial canal silt. High natural gluten elasticity, yielding pillowy, tender rotis.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-BALWINDER-02',
      farmerId: 'usr-balwinder-singh',
      farmerName: 'Balwinder Singh',
      farmerEmail: 'balwinder.singh@auricvista.farm',
      farmLocation: 'Singh Golden Fields Grain Farm, Ludhiana, Punjab',
      name: 'Traditional Royal Long-Grain Basmati Rice',
      category: 'Grains & Cereals',
      quantity: 190,
      unit: 'kg',
      price: 120,
      description: 'Aged 12 months, Himalayan snow-fed authentic long-grain Basmati paddy. Slender non-sticky grains expanding up to 2.5x length upon cooking.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-BALWINDER-03',
      farmerId: 'usr-balwinder-singh',
      farmerName: 'Balwinder Singh',
      farmerEmail: 'balwinder.singh@auricvista.farm',
      farmLocation: 'Singh Golden Fields Grain Farm, Ludhiana, Punjab',
      name: 'Fresh Winter Mustard Greens (Sarson Ka Saag)',
      category: 'Herbs & Leafy Greens',
      quantity: 70,
      unit: 'bunch',
      price: 25,
      description: 'Broad, peppery winter sarson leaves fresh-cut from Punjab fields at daybreak. Authentic base for traditional North Indian sarson saag.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-BALWINDER-04',
      farmerId: 'usr-balwinder-singh',
      farmerName: 'Balwinder Singh',
      farmerEmail: 'balwinder.singh@auricvista.farm',
      farmLocation: 'Singh Golden Fields Grain Farm, Ludhiana, Punjab',
      name: 'Crisp White Country Radish (Mooli)',
      category: 'Vegetables',
      quantity: 75,
      unit: 'kg',
      price: 25,
      description: 'Long, crisp white radishes with tender spicy crunch and high moisture. Harvested chemical-free from deep loose alluvial loam.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1592417817098-8f3d69109853?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-BALWINDER-05',
      farmerId: 'usr-balwinder-singh',
      farmerName: 'Balwinder Singh',
      farmerEmail: 'balwinder.singh@auricvista.farm',
      farmLocation: 'Singh Golden Fields Grain Farm, Ludhiana, Punjab',
      name: 'Organic Whole Yellow Mustard Seeds (Sarson)',
      category: 'Spices & Seasonings',
      quantity: 70,
      unit: 'kg',
      price: 110,
      description: 'Cleaned, bold yellow mustard seeds with pungent essential sinigrin oils. Essential for tempering, pickling, and artisanal mustard paste.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-BALWINDER-06',
      farmerId: 'usr-balwinder-singh',
      farmerName: 'Balwinder Singh',
      farmerEmail: 'balwinder.singh@auricvista.farm',
      farmLocation: 'Singh Golden Fields Grain Farm, Ludhiana, Punjab',
      name: 'Pure Stone-Ground Whole Wheat Atta',
      category: 'Grains & Cereals',
      quantity: 160,
      unit: 'kg',
      price: 60,
      description: 'Chakki-ground 100% whole grain flour from Punjab Sharbati wheat, retaining intact germ and bran for wholesome dietary fiber.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 6. KAVITA PATEL (Unjha & Junagadh, Gujarat) - Cumin, Garlic & Cold-Pressed Groundnut Oil
    // =========================================================================
    {
      id: 'PROD-KAVITA-01',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice & Cold-Press Mill, Unjha, Gujarat',
      name: 'Unjha Premium Whole Cumin Seeds (Jeera)',
      category: 'Spices & Seasonings',
      quantity: 115,
      unit: 'kg',
      price: 240,
      description: 'Machine-cleaned, sun-cured cumin seeds with deep earthy aroma and high cuminaldehyde essential oil content from the Unjha spice capital.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-KAVITA-02',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice & Cold-Press Mill, Junagadh, Gujarat',
      name: 'Cold-Pressed Groundnut Oil (Wood-Pressed Kacchi Ghani)',
      category: 'Organic & Natural',
      quantity: 130,
      unit: 'litre',
      price: 230,
      description: 'First-press unrefined groundnut oil extracted in wooden churns below 45°C. Retains natural nutty fragrance, plant sterols, and Vitamin E.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-KAVITA-03',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice & Cold-Press Mill, Unjha, Gujarat',
      name: 'Mandsaur Desi White Garlic (Lahsun)',
      category: 'Vegetables',
      quantity: 90,
      unit: 'kg',
      price: 140,
      description: 'Compact, firm multi-clove white garlic bulbs cured naturally under shade. High allicin concentration offering intense pungent aroma.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-KAVITA-04',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice & Cold-Press Mill, Junagadh, Gujarat',
      name: 'Giant White Kabuli Chickpeas (Chana)',
      category: 'Pulses & Dals',
      quantity: 100,
      unit: 'kg',
      price: 130,
      description: 'Extra bold 12mm+ premium Kabuli chana with creamy white seed coat. Soft melt-in-mouth texture when boiled, ideal for gourmet curries.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-KAVITA-05',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice & Cold-Press Mill, Unjha, Gujarat',
      name: 'Fragrant Green Fennel Seeds (Variyali / Saunf)',
      category: 'Spices & Seasonings',
      quantity: 75,
      unit: 'kg',
      price: 180,
      description: 'Natural emerald green fennel seeds rich in sweet anethole essential oil. Perfect after-meal digestive mouth freshener and baking spice.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-KAVITA-06',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice & Cold-Press Mill, Junagadh, Gujarat',
      name: 'Unpolished Desi Brown Chickpeas (Kala Chana)',
      category: 'Pulses & Dals',
      quantity: 85,
      unit: 'kg',
      price: 95,
      description: 'High-protein, low glycemic brown desi chickpeas grown in Saurashtra black cotton soil. Sun-cured with zero artificial polishing or dyes.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 7. MATHEW JOSEPH (Wayanad & Idukki, Kerala) - High-Altitude Spices & Virgin Coconut Oil
    // =========================================================================
    {
      id: 'PROD-MATHEW-01',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Idukki, Kerala',
      name: 'Malabar Tellicherry Bold Black Peppercorns',
      category: 'Spices & Seasonings',
      quantity: 65,
      unit: 'kg',
      price: 520,
      description: 'Extra bold 4.25mm black peppercorns from ancient vines with intense piperine bite and woody citrus undertones.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-MATHEW-02',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Idukki, Kerala',
      name: 'Idukki Extra Bold Green Cardamom (Elaichi)',
      category: 'Spices & Seasonings',
      quantity: 45,
      unit: 'kg',
      price: 1800,
      description: '8mm+ bold emerald green cardamom pods packed with fragrant essential oils, cineole, and sweet floral spice.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 10.0,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-MATHEW-03',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Wayanad, Kerala',
      name: 'Ceylon True Sweet Cinnamon Quills (Dalchini)',
      category: 'Spices & Seasonings',
      quantity: 50,
      unit: 'kg',
      price: 600,
      description: 'Ultra-thin multi-layered authentic Ceylon cinnamon quills with mild sweet woodsy flavor and low coumarin.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-MATHEW-04',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Wayanad, Kerala',
      name: 'Wayanad Fresh Rhizome Ginger (Adrak)',
      category: 'Vegetables',
      quantity: 70,
      unit: 'kg',
      price: 90,
      description: 'Plump aromatic ginger hands harvested fresh from highland slopes. Juicy, fibrous-free core with warming pungent gingerol.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-MATHEW-05',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Alappuzha, Kerala',
      name: 'Extra Virgin Cold-Pressed Coconut Oil (Marachekku)',
      category: 'Organic & Natural',
      quantity: 110,
      unit: 'litre',
      price: 280,
      description: 'Traditional stone-and-wood pressed pure coconut oil from fresh sun-dried copra with zero chemical refining or heat bleaching.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1544378730-8b5104b18790?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-MATHEW-06',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Vazhakulam, Kerala',
      name: 'Vazhakulam Giant Sweet Pineapples',
      category: 'Fruits',
      quantity: 65,
      unit: 'piece',
      price: 55,
      description: 'GI-tagged Vazhakulam Mauritius pineapples with intense golden flesh, low acidity, and crisp sweet center.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 8. RAMESHWAR LAL (Nagaur & Jodhpur, Rajasthan) - Coriander, Methi & Desert Pulses
    // =========================================================================
    {
      id: 'PROD-RAMESHWAR-01',
      farmerId: 'usr-rameshwar-lal',
      farmerName: 'Rameshwar Lal',
      farmerEmail: 'rameshwar.lal@auricvista.farm',
      farmLocation: 'Marwar Desert Bloom Agro Farm, Nagaur, Rajasthan',
      name: 'Nagaur Whole Dhaniya Seeds (Aromatic Coriander)',
      category: 'Spices & Seasonings',
      quantity: 95,
      unit: 'kg',
      price: 160,
      description: 'Round, aromatic Nagaur coriander seeds dried naturally under desert sun. Mild citrus notes with high essential linalool oil.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAMESHWAR-02',
      farmerId: 'usr-rameshwar-lal',
      farmerName: 'Rameshwar Lal',
      farmerEmail: 'rameshwar.lal@auricvista.farm',
      farmLocation: 'Marwar Desert Bloom Agro Farm, Nagaur, Rajasthan',
      name: 'Organic Methi Dana (Whole Fenugreek Seeds)',
      category: 'Spices & Seasonings',
      quantity: 80,
      unit: 'kg',
      price: 115,
      description: 'GI-grade Nagaur fenugreek seeds known worldwide for unmatched intense aroma and digestive galactomannan fiber.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAMESHWAR-03',
      farmerId: 'usr-rameshwar-lal',
      farmerName: 'Rameshwar Lal',
      farmerEmail: 'rameshwar.lal@auricvista.farm',
      farmLocation: 'Marwar Desert Bloom Agro Farm, Jodhpur, Rajasthan',
      name: 'Rajasthan Desi Pearl Millet (Bajra Grains)',
      category: 'Grains & Cereals',
      quantity: 150,
      unit: 'kg',
      price: 36,
      description: 'Hardy drought-resistant desert pearl millet grains. Abundant in magnesium, potassium, and slow-release low glycemic complex carbs.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAMESHWAR-04',
      farmerId: 'usr-rameshwar-lal',
      farmerName: 'Rameshwar Lal',
      farmerEmail: 'rameshwar.lal@auricvista.farm',
      farmLocation: 'Marwar Desert Bloom Agro Farm, Nagaur, Rajasthan',
      name: 'Split Yellow Moong Dal (Unpolished)',
      category: 'Pulses & Dals',
      quantity: 90,
      unit: 'kg',
      price: 135,
      description: 'Easy-to-digest light yellow split moong dal cultivated in desert sandy loam. Free from leather polishing, water treatment, or added colors.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAMESHWAR-05',
      farmerId: 'usr-rameshwar-lal',
      farmerName: 'Rameshwar Lal',
      farmerEmail: 'rameshwar.lal@auricvista.farm',
      farmLocation: 'Marwar Desert Bloom Agro Farm, Nagaur, Rajasthan',
      name: 'Whole Green Moong (Sabut Moong Dal)',
      category: 'Pulses & Dals',
      quantity: 95,
      unit: 'kg',
      price: 125,
      description: 'Small, vibrant green whole moong beans excellent for fresh sprouting and high-protein khichdi. Pure natural crop with high germination rate.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-RAMESHWAR-06',
      farmerId: 'usr-rameshwar-lal',
      farmerName: 'Rameshwar Lal',
      farmerEmail: 'rameshwar.lal@auricvista.farm',
      farmLocation: 'Marwar Desert Bloom Agro Farm, Jodhpur, Rajasthan',
      name: 'Marwar Desi Moth Beans (Matki Whole)',
      category: 'Pulses & Dals',
      quantity: 70,
      unit: 'kg',
      price: 110,
      description: 'Traditional drought-hardy Marwari moth beans. Nutty, protein-dense legume perfect for sprouting, traditional usal, and spiced curries.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 9. VENKATESH RAO (Guntur & Tenali, AP) - Chillies, Curry Leaves & Pulses
    // =========================================================================
    {
      id: 'PROD-VENKATESH-01',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Guntur, Andhra Pradesh',
      name: 'Guntur Teja Fiery Red Dry Chillies',
      category: 'Spices & Seasonings',
      quantity: 100,
      unit: 'kg',
      price: 220,
      description: 'World-famous Guntur S17 Teja whole dried red chillies. High capsaicin fiery heat and intense sharp bite with natural sun-cured deep crimson color.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VENKATESH-02',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Guntur, Andhra Pradesh',
      name: 'Guntur Spicy Green Chillies (Mirchi)',
      category: 'Vegetables',
      quantity: 75,
      unit: 'kg',
      price: 45,
      description: 'Slender, dark green chillies picked fresh at sunrise with taut, snappy skin and fiery capsaicin kick for authentic Andhra tempering.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1563865436874-9aef32095fad?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VENKATESH-03',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Tenali, Andhra Pradesh',
      name: 'Organic Fragrant Curry Leaves (Kadi Patta)',
      category: 'Herbs & Leafy Greens',
      quantity: 65,
      unit: 'bunch',
      price: 15,
      description: 'Freshly stripped tender dark green curry leaves from pesticide-free trees nurtured by Krishna river basin sediment. Rich in iron and aromatic oils.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VENKATESH-04',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Guntur, Andhra Pradesh',
      name: 'Guntur Whole Black Urad Dal (Gooty Urad)',
      category: 'Pulses & Dals',
      quantity: 115,
      unit: 'kg',
      price: 140,
      description: 'Nutritious unpolished whole black gram lentils with intact skin. Yields velvety, fluffy fermentation ideal for authentic crisp medu vadas and dosas.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VENKATESH-05',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Guntur, Andhra Pradesh',
      name: 'Split Washed White Urad Dal',
      category: 'Pulses & Dals',
      quantity: 85,
      unit: 'kg',
      price: 150,
      description: 'Premium de-husked split white urad dal. Non-chemical processing with zero synthetic brightening powders, perfect for soft fluffy idlis.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VENKATESH-06',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Guntur, Andhra Pradesh',
      name: 'Salem & Lakadong High-Curcumin Turmeric (Haldi)',
      category: 'Spices & Seasonings',
      quantity: 80,
      unit: 'kg',
      price: 180,
      description: 'Sun-dried pure whole turmeric fingers boasting 6.5%+ natural curcumin content, deep golden pigment, and zero lead chromate adulteration.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 10. GURPREET CHAHAL (Shimla & Solan, HP) - Mountain Apples & Cold-Climate Vegetables
    // =========================================================================
    {
      id: 'PROD-GURPREET-01',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Crisp Fruit Orchards, Shimla, Himachal Pradesh',
      name: 'Shimla Royal Delicious Mountain Apples',
      category: 'Fruits',
      quantity: 110,
      unit: 'kg',
      price: 130,
      description: 'Crisp, aromatic high-altitude red apples harvested from Himalayan mountain slopes with natural skin wax, fine honey aroma, and firm bite.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GURPREET-02',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Crisp Fruit Orchards, Solan, Himachal Pradesh',
      name: 'Shimla Crisp Green Capsicum (Bell Pepper)',
      category: 'Vegetables',
      quantity: 70,
      unit: 'kg',
      price: 50,
      description: 'Blocky, thick-walled four-lobed green bell peppers with crisp refreshing crunch. Nurtured by cool mountain air with zero pesticide residue.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1563865436874-9aef32095fad?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GURPREET-03',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Crisp Fruit Orchards, Solan, Himachal Pradesh',
      name: 'Himachal Sweet Green Peas (Matar in Pod)',
      category: 'Vegetables',
      quantity: 85,
      unit: 'kg',
      price: 65,
      description: 'Plump, tender sweet green peas hand-picked in pod from cold terrace gardens. Naturally sweet sugars preserved by morning mist picking.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1587735243615-c03f25aaff15?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GURPREET-04',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Crisp Fruit Orchards, Shimla, Himachal Pradesh',
      name: 'Pahari Red Farm Potatoes (Aloo)',
      category: 'Vegetables',
      quantity: 130,
      unit: 'kg',
      price: 30,
      description: 'Firm mountain red-skin potatoes with creamy yellow flesh and high dry matter. Unwaxed, untreated, perfect for roasting and rich curries.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GURPREET-05',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Crisp Fruit Orchards, Solan, Himachal Pradesh',
      name: 'Fresh Snowball Cauliflower (Phoolgobhi)',
      category: 'Vegetables',
      quantity: 55,
      unit: 'piece',
      price: 35,
      description: 'Tight, pure white snowball cauliflower curds surrounded by fresh protective green leaves. Chemical-free cold climate harvest.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GURPREET-06',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Crisp Fruit Orchards, Solan, Himachal Pradesh',
      name: 'Jammu Chitra Red Rajma (Kidney Beans)',
      category: 'Pulses & Dals',
      quantity: 80,
      unit: 'kg',
      price: 165,
      description: 'High-altitude speckled red Chitra kidney beans with thin skin that softens beautifully into thick, melt-in-the-mouth Kashmiri rajma gravy.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 11. SUBHASH MONDAL (Sundarbans, West Bengal) - Wild Mangrove Honey & Native Rice
    // =========================================================================
    {
      id: 'PROD-SUBHASH-01',
      farmerId: 'usr-subhash-mondal',
      farmerName: 'Subhash Mondal',
      farmerEmail: 'subhash.mondal@auricvista.farm',
      farmLocation: 'Mangrove Fringe Natural Reserve, Sundarbans, West Bengal',
      name: 'Sundarbans Wild Mangrove Multi-Floral Raw Honey',
      category: 'Organic & Natural',
      quantity: 85,
      unit: 'kg',
      price: 480,
      description: 'Ethically collected raw, unheated honey from wild mangrove forest blooms. Deep amber shade with therapeutic enzymes, bee pollen, and warm floral spice.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 10.0,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SUBHASH-02',
      farmerId: 'usr-subhash-mondal',
      farmerName: 'Subhash Mondal',
      farmerEmail: 'subhash.mondal@auricvista.farm',
      farmLocation: 'Mangrove Fringe Natural Reserve, Sundarbans, West Bengal',
      name: 'Gobindobhog Fragrant Short-Grain Baby Rice',
      category: 'Grains & Cereals',
      quantity: 110,
      unit: 'kg',
      price: 115,
      description: 'Heritage GI-tagged aromatic white baby rice traditionally used for sacred Bengali payesh, khichuri, and ghee bhat. Buttery floral fragrance.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SUBHASH-03',
      farmerId: 'usr-subhash-mondal',
      farmerName: 'Subhash Mondal',
      farmerEmail: 'subhash.mondal@auricvista.farm',
      farmLocation: 'Mangrove Fringe Natural Reserve, Sundarbans, West Bengal',
      name: 'Sundarbans Organic Black Rice (Kala Bhat)',
      category: 'Grains & Cereals',
      quantity: 65,
      unit: 'kg',
      price: 180,
      description: 'Ancestral heirloom black rice rich in anthocyanin purple antioxidants, iron, and fiber. Mild nutty flavor with gorgeous natural purple hue when steamed.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SUBHASH-04',
      farmerId: 'usr-subhash-mondal',
      farmerName: 'Subhash Mondal',
      farmerEmail: 'subhash.mondal@auricvista.farm',
      farmLocation: 'Mangrove Fringe Natural Reserve, Sundarbans, West Bengal',
      name: 'Bengal Fresh Green Pointed Gourd (Parwal / Potol)',
      category: 'Vegetables',
      quantity: 60,
      unit: 'kg',
      price: 45,
      description: 'Striped tender green pointed gourd picked at sunrise. Crisp seed cavity with delicate flavor, perfect for traditional potol dorma and light stir-fries.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SUBHASH-05',
      farmerId: 'usr-subhash-mondal',
      farmerName: 'Subhash Mondal',
      farmerEmail: 'subhash.mondal@auricvista.farm',
      farmLocation: 'Mangrove Fringe Natural Reserve, Sundarbans, West Bengal',
      name: 'Heritage Unpolished Brown Rice (Dheki-Chhata)',
      category: 'Grains & Cereals',
      quantity: 85,
      unit: 'kg',
      price: 85,
      description: 'Traditional wooden pestle (dheki) de-husked brown rice retaining complete nutrient-dense bran layer and germ with zero synthetic polish.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 12. ARUNACHALAM MURUGAN (Pollachi & Coimbatore, TN) - Coconuts, Moringa & Roots
    // =========================================================================
    {
      id: 'PROD-ARUN-01',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Coconut Estate, Pollachi, Tamil Nadu',
      name: 'Pollachi Fresh Tender Green Coconuts',
      category: 'Fruits',
      quantity: 135,
      unit: 'piece',
      price: 40,
      description: 'Plump Pollachi green coconuts packed with 450ml+ natural sweet isotonic coconut water and delicate soft malai. Harvested fresh from organic groves.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1544378730-8b5104b18790?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-ARUN-02',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Coconut Estate, Coimbatore, Tamil Nadu',
      name: 'Coimbatore Fresh Moringa Drumsticks',
      category: 'Vegetables',
      quantity: 80,
      unit: 'kg',
      price: 50,
      description: 'Long, fleshy, tender moringa drumsticks picked fresh from Anamalai foothill farms. High in plant calcium, Vitamin C, and bioflavonoids.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-ARUN-03',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Coconut Estate, Ooty, Tamil Nadu',
      name: 'Ooty Sweet Orange Carrots (Gajar)',
      category: 'Vegetables',
      quantity: 90,
      unit: 'kg',
      price: 45,
      description: 'Crisp, slender orange hill carrots grown in cool Nilgiris mountain soil. Juicy core with high natural beta-carotene and pleasant earthy sweetness.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-ARUN-04',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Coconut Estate, Ooty, Tamil Nadu',
      name: 'Ruby Red Organic Beetroot (Chukandar)',
      category: 'Vegetables',
      quantity: 75,
      unit: 'kg',
      price: 38,
      description: 'Deep ruby-red round roots fresh from hill terraces. Firm skin with high betalain pigments and natural dietary nitrates for peak vitality.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1592417817098-8f3d69109853?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-ARUN-05',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Coconut Estate, Kanyakumari, Tamil Nadu',
      name: 'Kanyakumari Whole Aromatic Cloves (Laung)',
      category: 'Spices & Seasonings',
      quantity: 35,
      unit: 'kg',
      price: 850,
      description: 'Hand-picked flower buds with intact rounded crown, high eugenol oil content, and warm spicy aroma from coastal Western Ghats.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-ARUN-06',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Coconut Estate, Pollachi, Tamil Nadu',
      name: 'Salem Fresh Tapioca Roots (Maravalli Kizhangu)',
      category: 'Vegetables',
      quantity: 65,
      unit: 'kg',
      price: 30,
      description: 'Freshly uprooted starchy cassava roots with snow-white flesh and zero bitter aftertaste. Rich in natural gluten-free dietary carbohydrates.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 13. PRADIP DESHMUKH (Nashik & Kolhapur, MH) - Storage Onions, Grapes & Jaggery
    // =========================================================================
    {
      id: 'PROD-PRADIP-01',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Vineyard & Sugar Estate, Nashik, Maharashtra',
      name: 'Nashik Red Storage Onions (Pyaz)',
      category: 'Vegetables',
      quantity: 170,
      unit: 'kg',
      price: 26,
      description: 'Firm, multi-layered dry-skin red onions grown in fertile Sahyadri soil. High dry matter, strong pungent aroma, and superior natural shelf stability.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-PRADIP-02',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Vineyard & Sugar Estate, Nashik, Maharashtra',
      name: 'Nashik Black Seedless Table Grapes',
      category: 'Fruits',
      quantity: 95,
      unit: 'kg',
      price: 85,
      description: 'Sweet, crisp black seedless grapes harvested from sun-drenched valley vines. Natural silvery bloom, firm pulp, and high resveratrol antioxidant.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-PRADIP-03',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Vineyard & Sugar Estate, Kolhapur, Maharashtra',
      name: 'Kolhapur Artisanal Sugarcane Jaggery (Organic Gur)',
      category: 'Organic & Natural',
      quantity: 115,
      unit: 'kg',
      price: 75,
      description: 'Solid golden jaggery blocks prepared by boiling fresh sugarcane juice in iron vats. Cleaned with wild bhendi extract; free from sulphur or artificial bleach.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1607349913338-fca6f7fc42d0?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-PRADIP-04',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Vineyard & Sugar Estate, Nagpur, Maharashtra',
      name: 'Nagpur Sweet Mandarin Oranges (Santra)',
      category: 'Fruits',
      quantity: 145,
      unit: 'kg',
      price: 70,
      description: 'Juicy, sun-ripened Nagpur santra with loose thin peel, sweet-tangy pulp, and high natural Vitamin C and bioflavonoids.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-PRADIP-05',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Vineyard & Sugar Estate, Solapur, Maharashtra',
      name: 'Bhagwa Ruby Red Pomegranates (Anaar)',
      category: 'Fruits',
      quantity: 80,
      unit: 'kg',
      price: 130,
      description: 'Bhagwa variety pomegranates filled with deep ruby arils, soft chewable seeds, and intense sweet juice rich in punicalagins.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-PRADIP-06',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Vineyard & Sugar Estate, Solapur, Maharashtra',
      name: 'Solapur White Sorghum Grain (Jowar Whole)',
      category: 'Grains & Cereals',
      quantity: 105,
      unit: 'kg',
      price: 45,
      description: 'Naturally drought-fed pearly white jowar grain. Gluten-free staple rich in copper, magnesium, and slow-release low glycemic carbohydrates.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },

    // =========================================================================
    // 14. GHULAM HASSAN MIR (Pampore & Sopore, J&K) - GI Saffron & Kashmiri Dry Fruits
    // =========================================================================
    {
      id: 'PROD-GHULAM-01',
      farmerId: 'usr-ghulam-mir',
      farmerName: 'Ghulam Hassan Mir',
      farmerEmail: 'ghulam.mir@auricvista.farm',
      farmLocation: 'Kashmir Valley Saffron Heritage, Pampore, Jammu & Kashmir',
      name: 'Pampore Mongra Grade-A1 Pure Saffron (Kesar)',
      category: 'Spices & Seasonings',
      quantity: 35,
      unit: 'piece',
      price: 280,
      description: 'GI-certified pure red Mongra stigma threads picked by hand at dawn in Pampore karewas. Crocin content > 220, intense royal crimson aroma.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 10.0,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GHULAM-02',
      farmerId: 'usr-ghulam-mir',
      farmerName: 'Ghulam Hassan Mir',
      farmerEmail: 'ghulam.mir@auricvista.farm',
      farmLocation: 'Kashmir Valley Saffron Heritage, Sopore, Jammu & Kashmir',
      name: 'Kashmiri Snow-White Walnut Kernels (Akhrot Giri)',
      category: 'Organic & Natural',
      quantity: 55,
      unit: 'kg',
      price: 950,
      description: 'Crisp, high-oil Kashmiri walnut halves freshly cracked from thin-shelled mountain trees. Zero chemical bleaching with buttery sweet taste.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GHULAM-03',
      farmerId: 'usr-ghulam-mir',
      farmerName: 'Ghulam Hassan Mir',
      farmerEmail: 'ghulam.mir@auricvista.farm',
      farmLocation: 'Kashmir Valley Saffron Heritage, Pampore, Jammu & Kashmir',
      name: 'Kashmiri Sweet Mamra Almonds (Badam Giri)',
      category: 'Organic & Natural',
      quantity: 48,
      unit: 'kg',
      price: 1200,
      description: 'Concave-shaped organic Mamra almonds cultivated in cold Kashmir karewas. Packed with 50%+ natural almond oil, Vitamin E, and neuro-nutrients.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GHULAM-04',
      farmerId: 'usr-ghulam-mir',
      farmerName: 'Ghulam Hassan Mir',
      farmerEmail: 'ghulam.mir@auricvista.farm',
      farmLocation: 'Kashmir Valley Saffron Heritage, Sopore, Jammu & Kashmir',
      name: 'Crisp Kashmiri Ambri Apples',
      category: 'Fruits',
      quantity: 70,
      unit: 'kg',
      price: 160,
      description: 'Native Kashmiri Ambri apples with blush-red skin and firm aromatic flesh. Renowned for rich floral fragrance, crisp sweetness, and long keeping quality.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GHULAM-05',
      farmerId: 'usr-ghulam-mir',
      farmerName: 'Ghulam Hassan Mir',
      farmerEmail: 'ghulam.mir@auricvista.farm',
      farmLocation: 'Kashmir Valley Saffron Heritage, Sopore, Jammu & Kashmir',
      name: 'Sun-Dried Kashmiri Dried Apricots (Khubani)',
      category: 'Organic & Natural',
      quantity: 45,
      unit: 'kg',
      price: 420,
      description: 'Sun-cured golden Kashmiri mountain apricots with sweet edible kernels inside. 100% natural, preservative-free, rich in iron and Vitamin A.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
  ];

  // Clean old diverse products to prevent legacy mismatch
  await query("DELETE FROM produce_listings WHERE id LIKE 'PROD-%';");

  for (const item of diverseListings) {
    const verifiedAsset = DATABASE_LISTING_ASSETS[item.id];
    const imageToStore = verifiedAsset ? JSON.stringify([verifiedAsset.image]) : item.images;

    await query(
      `INSERT INTO produce_listings (id, farmer_id, farmer_name, farmer_email, farm_location, name, category, quantity_available, unit, price, harvest_date, description, images, quality_score, freshness_label, status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, CURRENT_DATE, $11, $12, $13, $14, 'Active')
       ON CONFLICT (id) DO UPDATE SET
         farmer_id = EXCLUDED.farmer_id,
         farmer_name = EXCLUDED.farmer_name,
         farmer_email = EXCLUDED.farmer_email,
         farm_location = EXCLUDED.farm_location,
         name = EXCLUDED.name,
         category = EXCLUDED.category,
         quantity_available = EXCLUDED.quantity_available,
         unit = EXCLUDED.unit,
         price = EXCLUDED.price,
         description = EXCLUDED.description,
         images = EXCLUDED.images,
         quality_score = EXCLUDED.quality_score,
         freshness_label = EXCLUDED.freshness_label,
         status = 'Active';`,
      [
        item.id,
        item.farmerId,
        item.farmerName,
        item.farmerEmail,
        item.farmLocation,
        item.name,
        item.category,
        item.quantity,
        item.unit,
        item.price,
        item.description,
        imageToStore,
        item.qualityScore,
        item.freshnessLabel,
      ]
    );
  }

  console.log(`[Seed] Successfully seeded ${farmers.length} specialized regional farmers and ${diverseListings.length} realistic produce listings into PostgreSQL!`);
}

// Run immediately ONLY when executed directly
const isDirectRun = Boolean(
  process.argv[1] && (
    process.argv[1].endsWith('seed_diverse.ts') ||
    process.argv[1].endsWith('seed_diverse.js')
  )
);

if (isDirectRun) {
  seedDiverseMarketplace()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('[Seed Error]', err);
      process.exit(1);
    });
}
