import bcrypt from 'bcryptjs';
import { query } from './index';

export async function seedDiverseMarketplace() {
  console.log('[Seed] Starting comprehensive diverse marketplace population into PostgreSQL...');

  const defaultHash = await bcrypt.hash('FarmPass@2026', 10);
  const defaultPinHash = await bcrypt.hash('2026', 10);

  // 1. 15 Distinct Farmers Across India
  const farmers = [
    {
      userId: 'usr-ravi-kumar',
      farmerId: 'AV-FARM-1001',
      name: 'Ravi Kumar',
      email: 'ravi.kumar@auricvista.farm',
      role: 'farmer',
      phone: '+91 98450 12890',
      location: 'Chikkaballapur, Karnataka',
      farmName: 'Kumar Organic Red Soil Orchard',
      farmerSlug: 'ravi-kumar',
      mainCrops: 'Heirloom Vine Tomatoes, Baby Spinach, Golden Carrots, Sweet Kaddu',
      experience: '18 years',
      specialty: 'Organic Vegetables & Native Roots',
      acreage: '14 Acres Certified Natural',
      highlightBadge: 'Master Grower',
      description: 'Pioneer of chemical-free heirloom vegetable cultivation in the fertile red loam soil of Chikkaballapur.',
    },
    {
      userId: 'usr-lakshmi-devi',
      farmerId: 'AV-FARM-1002',
      name: 'Lakshmi Devi',
      email: 'lakshmi.devi@auricvista.farm',
      role: 'farmer',
      phone: '+91 94480 34120',
      location: 'Kolar, Karnataka',
      farmName: 'Devi Hydroponic & Exotic Fruit Orchards',
      farmerSlug: 'lakshmi-devi',
      mainCrops: 'Hydroponic Greens, Red Lady Papaya, Muskmelon',
      experience: '12 years',
      specialty: 'Hydroponic Greens & Exotic Melons',
      acreage: '8 Acres Precision Soil',
      highlightBadge: 'Zero Pesticide Pioneer',
      description: 'Specializes in nutrient-rich cold-water hydroponics and naturally ripened table fruits.',
    },
    {
      userId: 'usr-suresh-naidu',
      farmerId: 'AV-FARM-1003',
      name: 'Suresh Naidu',
      email: 'suresh.naidu@auricvista.farm',
      role: 'farmer',
      phone: '+91 98860 78234',
      location: 'Hosur Agro Ridge, Tamil Nadu / Karnataka',
      farmName: 'Naidu Ancestral Millet & Pulse Reserve',
      farmerSlug: 'suresh-naidu',
      mainCrops: 'Finger Millet (Ragi), Desi Toor Dal, Country Gourds',
      experience: '22 years',
      specialty: 'Heritage Millets, Pulses & Native Grains',
      acreage: '26 Acres Ancestral Farm',
      highlightBadge: 'Heritage Cultivator',
      description: 'Preserves native drought-resistant millet seeds and unpolished heirloom lentils without synthetic chemicals.',
    },
    {
      userId: 'usr-nitin-patil',
      farmerId: 'AV-FARM-1004',
      name: 'Nitin Patil',
      email: 'nitin.patil@auricvista.farm',
      role: 'farmer',
      phone: '+91 98220 54321',
      location: 'Ratnagiri & Mahabaleshwar, Maharashtra',
      farmName: 'Patil Konkan Coast Agro Orchards',
      farmerSlug: 'nitin-patil',
      mainCrops: 'Ratnagiri Alphonso Mangoes, Dahanu Sapota, Strawberries',
      experience: '25 years',
      specialty: 'GI-Tagged Alphonso Mangoes & Berries',
      acreage: '30 Acres Coastal Laterite Soil',
      highlightBadge: 'GI Tagged Specialist',
      description: 'Award-winning Alphonso grower adhering strictly to tree-ripened, calcium-carbide-free harvesting.',
    },
    {
      userId: 'usr-balwinder-singh',
      farmerId: 'AV-FARM-1005',
      name: 'Balwinder Singh',
      email: 'balwinder.singh@auricvista.farm',
      role: 'farmer',
      phone: '+91 98140 67890',
      location: 'Ludhiana, Punjab',
      farmName: 'Singh Golden Fields Grain Farm',
      farmerSlug: 'balwinder-singh',
      mainCrops: 'Sharbati Golden Wheat, Basmati Rice, Mustard, White Radish',
      experience: '30 years',
      specialty: 'Organic Golden Wheat & Dehradun Basmati',
      acreage: '45 Acres Alluvial Soil',
      highlightBadge: 'Grain Champion',
      description: 'Dedicated to soil microbiology restoration and non-GMO high-protein wheat and aromatic long-grain paddy.',
    },
    {
      userId: 'usr-kavita-patel',
      farmerId: 'AV-FARM-1006',
      name: 'Kavita Patel',
      email: 'kavita.patel@auricvista.farm',
      role: 'farmer',
      phone: '+91 98790 12345',
      location: 'Unjha & Junagadh, Gujarat',
      farmName: 'Patel Natural Spice & Cold-Press Mill',
      farmerSlug: 'kavita-patel',
      mainCrops: 'Unjha Cumin (Jeera), Groundnut Oil, Kabuli Chickpeas',
      experience: '15 years',
      specialty: 'Sun-Dried Cumin, Garlic & Cold-Pressed Oils',
      acreage: '18 Acres Saurashtra Black Soil',
      highlightBadge: 'Spice Guild Master',
      description: 'Produces export-quality unadulterated essential spices and single-origin wood-pressed edible oils.',
    },
    {
      userId: 'usr-mathew-joseph',
      farmerId: 'AV-FARM-1007',
      name: 'Mathew Joseph',
      email: 'mathew.joseph@auricvista.farm',
      role: 'farmer',
      phone: '+91 94470 98765',
      location: 'Wayanad & Idukki, Kerala',
      farmName: 'Highland Mist Spice & Rainforest Plantation',
      farmerSlug: 'mathew-joseph',
      mainCrops: 'Tellicherry Black Pepper, Green Cardamom, Fresh Ginger, Pineapples',
      experience: '20 years',
      specialty: 'High-Altitude Spices & Virgin Coconut Oil',
      acreage: '22 Acres High Range Agro-Forest',
      highlightBadge: 'Rainforest Certified',
      description: 'Cultivates biodiversity-shaded spices in the misty Western Ghats under strict organic permaculture.',
    },
    {
      userId: 'usr-rameshwar-lal',
      farmerId: 'AV-FARM-1008',
      name: 'Rameshwar Lal',
      email: 'rameshwar.lal@auricvista.farm',
      role: 'farmer',
      phone: '+91 94140 45678',
      location: 'Nagaur & Jodhpur, Rajasthan',
      farmName: 'Marwar Desert Bloom Agro Farm',
      farmerSlug: 'rameshwar-lal',
      mainCrops: 'Whole Dhaniya Seeds, Organic Methi Dana, Desert Bajra',
      experience: '28 years',
      specialty: 'Aromatic Coriander, Methi & Desert Millets',
      acreage: '35 Acres Arid Organic Soil',
      highlightBadge: 'Desert Farming Hero',
      description: 'Harnesses traditional water harvesting to grow intensely fragrant desert spices and drought-hardy millets.',
    },
    {
      userId: 'usr-venkatesh-rao',
      farmerId: 'AV-FARM-1009',
      name: 'Venkatesh Rao',
      email: 'venkatesh.rao@auricvista.farm',
      role: 'farmer',
      phone: '+91 98480 33445',
      location: 'Guntur & Tenali, Andhra Pradesh',
      farmName: 'Krishna Delta Natural Farm',
      farmerSlug: 'venkatesh-rao',
      mainCrops: 'Spicy Green Chillies, Curry Leaves, Black Urad Dal',
      experience: '16 years',
      specialty: 'Direct Farm Chillies, Fresh Curry Leaves & Pulses',
      acreage: '20 Acres Krishna River Basin',
      highlightBadge: 'Delta Harvest Leader',
      description: 'Supplies high-heat chemical-free chillies and fragrant culinary greens nurtured by rich river sediment.',
    },
    {
      userId: 'usr-gurpreet-chahal',
      farmerId: 'AV-FARM-1010',
      name: 'Gurpreet Chahal',
      email: 'gurpreet.chahal@auricvista.farm',
      role: 'farmer',
      phone: '+91 98160 88990',
      location: 'Shimla & Solan, Himachal Pradesh',
      farmName: 'Himalayan Ridge Crisp Fruit Orchards',
      farmerSlug: 'gurpreet-chahal',
      mainCrops: 'Shimla Royal Delicious Apples, Sweet Green Peas, Green Capsicum',
      experience: '19 years',
      specialty: 'High-Altitude Apples & Cold-Climate Vegetables',
      acreage: '16 Acres Mountain Terrace',
      highlightBadge: 'Himalayan Orchardist',
      description: 'Mountain-stream irrigated snow-climate apples and tender winter pods picked at peak sugar content.',
    },
    {
      userId: 'usr-subhash-mondal',
      farmerId: 'AV-FARM-1011',
      name: 'Subhash Mondal',
      email: 'subhash.mondal@auricvista.farm',
      role: 'farmer',
      phone: '+91 98300 22334',
      location: 'Sundarbans, West Bengal',
      farmName: 'Mangrove Fringe Natural Reserve',
      farmerSlug: 'subhash-mondal',
      mainCrops: 'Wild Forest Raw Honey, Heritage Paddy',
      experience: '24 years',
      specialty: 'Ethical Wild Mangrove Honey & Native Rice',
      acreage: '12 Acres Forest Fringe',
      highlightBadge: 'Bio-Heritage Guardian',
      description: 'Harvests unfiltered, unheated wild raw honey directly from mangrove floral blooms in the Sundarbans biosphere.',
    },
    {
      userId: 'usr-arunachalam-murugan',
      farmerId: 'AV-FARM-1012',
      name: 'Arunachalam Murugan',
      email: 'arunachalam.murugan@auricvista.farm',
      role: 'farmer',
      phone: '+91 94430 77889',
      location: 'Pollachi & Coimbatore, Tamil Nadu',
      farmName: 'Anamalai Foothills Coconut & Moringa Estate',
      farmerSlug: 'arunachalam-murugan',
      mainCrops: 'Pollachi Fresh Coconuts, Moringa Drumsticks, Nilgiri Carrots',
      experience: '21 years',
      specialty: 'Nutrient-Dense Coconuts & Fresh Drumsticks',
      acreage: '28 Acres Foothill Loam',
      highlightBadge: 'Tree-Crop Specialist',
      description: 'Tender sweet coconuts and high-protein moringa pods cultivated with natural composting and drip irrigation.',
    },
    {
      userId: 'usr-pradip-deshmukh',
      farmerId: 'AV-FARM-1013',
      name: 'Pradip Deshmukh',
      email: 'pradip.deshmukh@auricvista.farm',
      role: 'farmer',
      phone: '+91 98230 11223',
      location: 'Nashik & Kolhapur, Maharashtra',
      farmName: 'Sahyadri Valley Vineyard & Sugar Estate',
      farmerSlug: 'pradip-deshmukh',
      mainCrops: 'Nashik Red Onions, Seedless Table Grapes, Kolhapur Jaggery',
      experience: '26 years',
      specialty: 'Storage Onions, Table Grapes & Artisanal Jaggery',
      acreage: '32 Acres Sahyadri Foothill',
      highlightBadge: 'Agri-Processing Leader',
      description: 'Known for high-dry-matter storage onions, sweet table grapes, and preservative-free solid sugarcane jaggery.',
    },
    {
      userId: 'usr-ghulam-mir',
      farmerId: 'AV-FARM-1015',
      name: 'Ghulam Hassan Mir',
      email: 'ghulam.mir@auricvista.farm',
      role: 'farmer',
      phone: '+91 94190 66778',
      location: 'Pampore & Sopore, Jammu & Kashmir',
      farmName: 'Kashmir Valley Saffron & Walnut Heritage',
      farmerSlug: 'ghulam-mir',
      mainCrops: 'Kashmir Kesar Saffron, Snow White Walnut Kernels',
      experience: '35 years',
      specialty: 'GI-Tagged Pampore Saffron & Kashmiri Walnuts',
      acreage: '10 Acres Karewa Soil',
      highlightBadge: 'Heritage Saffron Master',
      description: 'Fourth-generation saffron grower picking purple crocus flowers by hand during the autumn dawn harvest.',
    },
  ];

  for (const f of farmers) {
    await query(
      `INSERT INTO users (id, farmer_id, name, email, password_hash, pin_hash, role, phone, location, farm_name, main_crops)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
       ON CONFLICT (email) DO UPDATE SET 
         password_hash = EXCLUDED.password_hash,
         farmer_id = COALESCE(users.farmer_id, EXCLUDED.farmer_id),
         location = EXCLUDED.location,
         farm_name = EXCLUDED.farm_name,
         main_crops = EXCLUDED.main_crops;`,
      [f.userId, f.farmerId, f.name, f.email, defaultHash, defaultPinHash, f.role, f.phone, f.location, f.farmName, f.mainCrops]
    );

    await query(
      `INSERT INTO farmer_profiles (id, user_id, farmer_slug, farm_name, location, experience, specialty, acreage, highlight_badge, description, verification_status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'verified')
       ON CONFLICT (farmer_slug) DO UPDATE SET
         farm_name = EXCLUDED.farm_name,
         location = EXCLUDED.location,
         specialty = EXCLUDED.specialty,
         acreage = EXCLUDED.acreage,
         highlight_badge = EXCLUDED.highlight_badge,
         description = EXCLUDED.description;`,
      [
        `prof-${f.farmerSlug}`,
        f.userId,
        f.farmerSlug,
        f.farmName,
        f.location,
        f.experience,
        f.specialty,
        f.acreage,
        f.highlightBadge,
        f.description,
      ]
    );
  }

  // 2. 60+ Realistic, Distinct Indian Farm Produce Listings
  const diverseListings = [
    // === FRUITS ===
    {
      id: 'PROD-FRUIT-01',
      farmerId: 'usr-nitin-patil',
      farmerName: 'Nitin Patil',
      farmerEmail: 'nitin.patil@auricvista.farm',
      farmLocation: 'Patil Konkan Agro Orchards, Ratnagiri, Maharashtra',
      name: 'Ratnagiri Alphonso Mangoes (GI Tagged)',
      category: 'Fruits',
      quantity: 120,
      unit: 'dozen',
      price: 650,
      description: 'Naturally tree-ripened, golden-hued export grade Alphonso mangoes with rich saffron aroma and zero artificial ripening chemicals.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-02',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Orchard, Sirsi, Karnataka',
      name: 'Robusta Mountain Bananas (Fresh Bunch)',
      category: 'Fruits',
      quantity: 95,
      unit: 'dozen',
      price: 45,
      description: 'Sweet, potassium-rich mountain robusta bananas freshly harvested from rain-fed hillside plantations.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-03',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Vineyard & Orchards, Nagpur, Maharashtra',
      name: 'Nagpur Sweet Mandarin Oranges (Santra)',
      category: 'Fruits',
      quantity: 140,
      unit: 'kg',
      price: 70,
      description: 'Juicy, sun-ripened Nagpur santra with loose thin peel, sweet-tangy pulp, and high natural Vitamin C.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.5,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-04',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Vazhakulam, Kerala',
      name: 'Vazhakulam Giant Sweet Pineapples',
      category: 'Fruits',
      quantity: 60,
      unit: 'piece',
      price: 55,
      description: 'GI-tagged Vazhakulam Mauritius pineapples with intense golden flesh, low acidity, and crisp sweet center.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-05',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Crisp Fruit Orchards, Shimla, Himachal Pradesh',
      name: 'Shimla Royal Delicious Mountain Apples',
      category: 'Fruits',
      quantity: 110,
      unit: 'kg',
      price: 130,
      description: 'Crisp, aromatic high-altitude red apples harvested from Himalayan mountain slopes with natural skin wax and firm bite.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-06',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic & Exotic Fruit Orchards, Kolar, Karnataka',
      name: 'Red Lady Honey-Sweet Papaya',
      category: 'Fruits',
      quantity: 75,
      unit: 'kg',
      price: 40,
      description: 'Deep salmon-red flesh papaya with high papain digestive enzyme levels and honey-sweet natural flavor.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1617112848923-cc2234396a8d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.4,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-07',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Vineyard & Orchards, Solapur, Maharashtra',
      name: 'Bhagwa Ruby Red Pomegranates (Anaar)',
      category: 'Fruits',
      quantity: 85,
      unit: 'kg',
      price: 120,
      description: 'Deep red arils with soft seeds, high antioxidant content, and balanced sweet-tart refreshing juice.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1541344999736-83eca872f241?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-08',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Koppal, Karnataka',
      name: 'Sugar Baby Striped Watermelon',
      category: 'Fruits',
      quantity: 90,
      unit: 'piece',
      price: 60,
      description: 'Sun-drenched crisp red watermelons harvested at peak brix sugar level for ultimate hydration.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.5,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-09',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic & Exotic Fruit Orchards, Kolar, Karnataka',
      name: 'Honey Sweet Muskmelon (Kharbuja)',
      category: 'Fruits',
      quantity: 50,
      unit: 'kg',
      price: 45,
      description: 'Fragrant netted cantaloupe with soft orange sweet flesh and cooling summer electrolytes.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1571575179703-4995540a5a67?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.3,
      freshnessLabel: 'Good',
    },
    {
      id: 'PROD-FRUIT-10',
      farmerId: 'usr-rameshwar-lal',
      farmerName: 'Rameshwar Lal',
      farmerEmail: 'rameshwar.lal@auricvista.farm',
      farmLocation: 'Marwar Desert Bloom Agro Farm, Prayagraj / Nagaur',
      name: 'Allahabad Safeda Crisp White Guava',
      category: 'Fruits',
      quantity: 65,
      unit: 'kg',
      price: 55,
      description: 'Fragrant white-fleshed safeda guavas rich in dietary fiber and vitamin C with a refreshing floral aroma.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1536511135899-7c87c067885b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.4,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-11',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Vineyard, Nashik, Maharashtra',
      name: 'Nashik Black Seedless Table Grapes',
      category: 'Fruits',
      quantity: 80,
      unit: 'kg',
      price: 90,
      description: 'Plump, crunchy black seedless grapes freshly hand-clipped from Nashik hillside trellis vineyards.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596363505729-4190a9506133?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-12',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Haveri, Karnataka',
      name: 'Natural Red Dragon Fruit (Pitaya)',
      category: 'Fruits',
      quantity: 40,
      unit: 'kg',
      price: 140,
      description: 'Vibrant magenta-fleshed dragon fruit rich in betalain antioxidants and crunchy prebiotic seeds.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1527137342181-19aab11a8ee8?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-13',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Mahabubnagar / Tenali',
      name: 'Balanagar Sweet Custard Apple (Seethaphal)',
      category: 'Fruits',
      quantity: 35,
      unit: 'kg',
      price: 95,
      description: 'Creamy, sweet custard apples with thick knobby rind and fragrant pulp harvested at dawn.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1590779033100-9f60a05a013d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.5,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-14',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Estate, Pollachi, Tamil Nadu',
      name: 'Pollachi Fresh Tender Green Coconuts',
      category: 'Fruits',
      quantity: 150,
      unit: 'piece',
      price: 45,
      description: 'Filled with 400ml+ of sweet electrolyte-rich natural coconut water and soft tender malai.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1544378730-8b5104b18790?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-15',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Tenali, Andhra Pradesh',
      name: 'Kagzi Thin-Skin Fresh Juicy Lemons (Nimboo)',
      category: 'Fruits',
      quantity: 70,
      unit: 'kg',
      price: 60,
      description: 'Thin-skinned, seed-light aromatic yellow lemons packed with natural citric acidity and juice.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.4,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-FRUIT-16',
      farmerId: 'usr-nitin-patil',
      farmerName: 'Nitin Patil',
      farmerEmail: 'nitin.patil@auricvista.farm',
      farmLocation: 'Patil Konkan Agro Orchards, Mahabaleshwar, Maharashtra',
      name: 'Mahabaleshwar Fresh Sweet Strawberries',
      category: 'Fruits',
      quantity: 45,
      unit: 'box',
      price: 110,
      description: 'Fragrant deep-red hill strawberries picked fresh with green calyx intact and high natural sugar.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },

    // === VEGETABLES ===
    {
      id: 'PROD-VEG-01',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Estate, Nashik, Maharashtra',
      name: 'Nashik Red Storage Onions (Pyaz)',
      category: 'Vegetables',
      quantity: 200,
      unit: 'kg',
      price: 28,
      description: 'Firm, dry-skinned pungent red onions with excellent shelf life and concentrated culinary depth.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-02',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Orchard, Hassan, Karnataka',
      name: 'Pahari Red Farm Potatoes (Aloo)',
      category: 'Vegetables',
      quantity: 180,
      unit: 'kg',
      price: 26,
      description: 'Thin-skinned unpolished high-starch earth potatoes ideal for traditional Indian curries and roasting.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.5,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-03',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Orchard, Chikkaballapur, Karnataka',
      name: 'Heirloom Vine Tomatoes (Tamatar)',
      category: 'Vegetables',
      quantity: 140,
      unit: 'kg',
      price: 32,
      description: 'Sun-kissed red heirloom tomatoes harvested at dawn with exceptional sweetness and high natural lycopene.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-04',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Belagavi, Karnataka',
      name: 'Fresh Snowball Cauliflower (Phoolgobhi)',
      category: 'Vegetables',
      quantity: 70,
      unit: 'piece',
      price: 35,
      description: 'Tightly packed bright white curd cauliflower protected by crisp outer leaves with zero insect blemish.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-05',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Estate, Ooty, Tamil Nadu',
      name: 'Crisp Green Mountain Cabbage (Pattagobhi)',
      category: 'Vegetables',
      quantity: 85,
      unit: 'piece',
      price: 30,
      description: 'Dense, crunchy green cabbage heads harvested from the cool Nilgiri hill slopes.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.5,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-06',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Crisp Fruit Orchards, Shimla, Himachal Pradesh',
      name: 'Shimla Crisp Green Capsicum (Bell Pepper)',
      category: 'Vegetables',
      quantity: 60,
      unit: 'kg',
      price: 55,
      description: 'Glossy thick-walled green bell peppers with crisp juicy texture and aromatic sweetness.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-07',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Guntur, Andhra Pradesh',
      name: 'Guntur Spicy Green Chillies (Mirchi)',
      category: 'Vegetables',
      quantity: 50,
      unit: 'kg',
      price: 45,
      description: 'Freshly picked slender spicy green chillies delivering fiery pungent aroma for Indian tadka and curries.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-08',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Estate, Nilgiris, Tamil Nadu',
      name: 'Ooty Sweet Orange Carrots (Gajar)',
      category: 'Vegetables',
      quantity: 110,
      unit: 'kg',
      price: 48,
      description: 'Naturally sweet and crunchy orange carrots grown in black humus soil of the Nilgiri hills.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-09',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Estate, Madurai, Tamil Nadu',
      name: 'Ruby Red Organic Beetroot (Chukandar)',
      category: 'Vegetables',
      quantity: 80,
      unit: 'kg',
      price: 42,
      description: 'Earthy, mineral-rich deep ruby beetroots excellent for fresh juicing and healthy salads.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-10',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Mysuru, Karnataka',
      name: 'Mysore Long Purple Brinjal (Baingan)',
      category: 'Vegetables',
      quantity: 65,
      unit: 'kg',
      price: 38,
      description: 'Glossy slender purple eggplants with tender skin and creamy seed-light flesh for ennegai and sambar.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1628773822503-930a84d9f67a?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.4,
      freshnessLabel: 'Good',
    },
    {
      id: 'PROD-VEG-11',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Orchard, Mandya, Karnataka',
      name: 'Tender Green Okra / Ladies Finger (Bhindi)',
      category: 'Vegetables',
      quantity: 75,
      unit: 'kg',
      price: 45,
      description: 'Crisp, slender non-fibrous tender bhindi pods harvested early morning for crisp stir-fries.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1425543103986-22abb7d7e8d2?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-12',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic Greenhouses, Kolar, Karnataka',
      name: 'Crisp Green Country Cucumbers (Kheera)',
      category: 'Vegetables',
      quantity: 90,
      unit: 'kg',
      price: 30,
      description: 'Hydrating, cool field cucumbers with thin edible skin and zero bitterness.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.5,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-13',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Chitradurga, Karnataka',
      name: 'Fresh Country Bottle Gourd (Lauki)',
      category: 'Vegetables',
      quantity: 55,
      unit: 'piece',
      price: 35,
      description: 'Pale green cylindrical tender bottle gourds rich in dietary water and soothing digestive properties.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1597362925123-77861d3fbac7?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.4,
      freshnessLabel: 'Good',
    },
    {
      id: 'PROD-VEG-14',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Wayanad, Kerala',
      name: 'Organic Bitter Gourd (Karela)',
      category: 'Vegetables',
      quantity: 45,
      unit: 'kg',
      price: 48,
      description: 'Dark green ridged bitter gourd with high charantin and polypeptide-p for natural blood sugar wellness.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-15',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Orchards, Solan, Himachal Pradesh',
      name: 'Himachal Sweet Green Peas (Matar in Pod)',
      category: 'Vegetables',
      quantity: 80,
      unit: 'kg',
      price: 65,
      description: 'Crisp green pods bursting with sweet tender peas freshly picked in the cool Himalayan valleys.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1587735243615-c03f25aaff15?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-16',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Estate, Coimbatore, Tamil Nadu',
      name: 'Coimbatore Fresh Moringa Drumsticks',
      category: 'Vegetables',
      quantity: 90,
      unit: 'kg',
      price: 50,
      description: 'Long tender nutrient-dense drumsticks with thick fleshy pulp for authentic South Indian sambar.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-17',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Wayanad, Kerala',
      name: 'Wayanad Fresh Rhizome Ginger (Adrak)',
      category: 'Vegetables',
      quantity: 70,
      unit: 'kg',
      price: 90,
      description: 'Plump, fibrous-light aromatic fresh ginger with high gingerol content and sharp spicy zest.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-VEG-18',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice Farm, Mandsaur, Madhya Pradesh',
      name: 'Mandsaur Desi White Garlic (Lahsun)',
      category: 'Vegetables',
      quantity: 85,
      unit: 'kg',
      price: 110,
      description: 'Tight-cloved, highly aromatic white garlic bulbs with intense allicin flavor and high medicinal oil content.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },

    // === SPICES & SEASONINGS ===
    {
      id: 'PROD-SPICE-01',
      farmerId: 'usr-gopal-mahapatra',
      farmerName: 'Gopal Mahapatra',
      farmerEmail: 'gopal.mahapatra@auricvista.farm',
      farmLocation: 'Koraput Hill Agro Reserve, Odisha',
      name: 'Salem & Lakadong High-Curcumin Turmeric (Haldi)',
      category: 'Spices & Seasonings',
      quantity: 90,
      unit: 'kg',
      price: 180,
      description: 'Sun-dried pure whole turmeric fingers boasting 6.5%+ natural curcumin content and deep golden pigment.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SPICE-02',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Idukki, Kerala',
      name: 'Malabar Tellicherry Bold Black Peppercorns',
      category: 'Spices & Seasonings',
      quantity: 60,
      unit: 'kg',
      price: 520,
      description: 'Extra bold 4.25mm black peppercorns from ancient vines with intense piperine bite and woody citrus undertones.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SPICE-03',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Idukki, Kerala',
      name: 'Idukki Extra Bold Green Cardamom (Elaichi)',
      category: 'Spices & Seasonings',
      quantity: 40,
      unit: 'kg',
      price: 1800,
      description: '8mm+ bold emerald green cardamom pods packed with fragrant essential oils, cineole, and sweet floral spice.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 10.0,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SPICE-04',
      farmerId: 'usr-arunachalam-murugan',
      farmerName: 'Arunachalam Murugan',
      farmerEmail: 'arunachalam.murugan@auricvista.farm',
      farmLocation: 'Anamalai Foothills Estate, Kanyakumari, Tamil Nadu',
      name: 'Kanyakumari Whole Aromatic Cloves (Laung)',
      category: 'Spices & Seasonings',
      quantity: 35,
      unit: 'kg',
      price: 850,
      description: 'Hand-picked flower buds with intact rounded crown, high eugenol oil content, and warm spicy aroma.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SPICE-05',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Wayanad, Kerala',
      name: 'Ceylon True Sweet Cinnamon Quills (Dalchini)',
      category: 'Spices & Seasonings',
      quantity: 45,
      unit: 'kg',
      price: 600,
      description: 'Ultra-thin multi-layered authentic Ceylon cinnamon quills with mild sweet woodsy flavor and low coumarin.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SPICE-06',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice Farm, Unjha, Gujarat',
      name: 'Unjha Premium Whole Cumin Seeds (Jeera)',
      category: 'Spices & Seasonings',
      quantity: 110,
      unit: 'kg',
      price: 240,
      description: 'Machine-cleaned, sun-cured cumin seeds with deep earthy aroma and high cuminaldehyde essential oil.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SPICE-07',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Byadgi, Karnataka',
      name: 'Byadgi Wrinkled Mild Red Chillies',
      category: 'Spices & Seasonings',
      quantity: 80,
      unit: 'kg',
      price: 260,
      description: 'GI-tagged deep red crinkled Byadgi chillies offering vibrant natural red color and gentle aromatic heat.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-SPICE-08',
      farmerId: 'usr-ghulam-mir',
      farmerName: 'Ghulam Hassan Mir',
      farmerEmail: 'ghulam.mir@auricvista.farm',
      farmLocation: 'Kashmir Valley Saffron Heritage, Pampore, Kashmir',
      name: 'Pampore Mongra Grade-A1 Pure Saffron (Kesar)',
      category: 'Spices & Seasonings',
      quantity: 5,
      unit: 'piece',
      price: 350,
      description: 'Unadulterated all-red stigmas of Crocus sativus harvested from the high karewas of Kashmir with royal aroma.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 10.0,
      freshnessLabel: 'Excellent',
    },

    // === GRAINS & CEREALS ===
    {
      id: 'PROD-GRAIN-01',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Raichur, Karnataka',
      name: 'Sona Masoori Raw Unpolished Rice (Chawal)',
      category: 'Grains & Cereals',
      quantity: 350,
      unit: 'kg',
      price: 65,
      description: 'Medium-grain aromatic lightweight paddy aged for 12 months for non-sticky, fluffy daily rice meals.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GRAIN-02',
      farmerId: 'usr-balwinder-singh',
      farmerName: 'Balwinder Singh',
      farmerEmail: 'balwinder.singh@auricvista.farm',
      farmLocation: 'Singh Golden Fields, Dehradun / Gurdaspur',
      name: 'Traditional Royal Long-Grain Basmati Rice',
      category: 'Grains & Cereals',
      quantity: 280,
      unit: 'kg',
      price: 125,
      description: 'Naturally aged extra-long slender basmati grains that elongate to double length with enchanting aroma.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GRAIN-03',
      farmerId: 'usr-balwinder-singh',
      farmerName: 'Balwinder Singh',
      farmerEmail: 'balwinder.singh@auricvista.farm',
      farmLocation: 'Singh Golden Fields, Sehore / Ludhiana',
      name: 'Sehore Sharbati Golden Wheat Grains (Gehu)',
      category: 'Grains & Cereals',
      quantity: 400,
      unit: 'kg',
      price: 45,
      description: 'Lustrous, heavy golden wheat grains rich in natural gluten and sweetness, yielding exceptionally soft rotis.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GRAIN-04',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Orchard, Mandya, Karnataka',
      name: 'Mandya Whole Finger Millet (Ragi Whole Grain)',
      category: 'Grains & Cereals',
      quantity: 250,
      unit: 'kg',
      price: 52,
      description: 'Calcium-dense ancient red ragi grains harvested from non-irrigated drylands, ideal for ragi mudde and health porridge.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GRAIN-05',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Estate, Solapur, Maharashtra',
      name: 'Solapur White Sorghum Grain (Jowar Whole)',
      category: 'Grains & Cereals',
      quantity: 180,
      unit: 'kg',
      price: 50,
      description: 'Gluten-free pearl-white sorghum grains cultivated in the Deccan plateau for authentic bhakri and flatbreads.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-GRAIN-06',
      farmerId: 'usr-rameshwar-lal',
      farmerName: 'Rameshwar Lal',
      farmerEmail: 'rameshwar.lal@auricvista.farm',
      farmLocation: 'Marwar Desert Bloom Farm, Barmer, Rajasthan',
      name: 'Rajasthan Desi Pearl Millet (Bajra Grains)',
      category: 'Grains & Cereals',
      quantity: 220,
      unit: 'kg',
      price: 38,
      description: 'Iron-rich desert millet harvested from organic dryland farms, perfect for winter khichdi and traditional rotla.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.5,
      freshnessLabel: 'Excellent',
    },

    // === PULSES & DALS ===
    {
      id: 'PROD-PULSE-01',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Kalaburagi, Karnataka',
      name: 'Gulbarga Desi Unpolished Toor Dal (Arhar)',
      category: 'Pulses & Dals',
      quantity: 200,
      unit: 'kg',
      price: 155,
      description: 'GI-tagged unpolished pigeon peas from the black soil of Gulbarga with high protein and earthy creamy texture.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1585994192701-f1a505c8574a?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-PULSE-02',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice Farm, Indore, Madhya Pradesh',
      name: 'Split Yellow Moong Dal (Unpolished)',
      category: 'Pulses & Dals',
      quantity: 160,
      unit: 'kg',
      price: 130,
      description: 'Easy-to-digest light yellow split lentils with no chemical oil polishing or synthetic coloring.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1585994192701-f1a505c8574a?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-PULSE-03',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Guntur, Andhra Pradesh',
      name: 'Guntur Whole Black Urad Dal (Gooty Urad)',
      category: 'Pulses & Dals',
      quantity: 140,
      unit: 'kg',
      price: 145,
      description: 'Unpolished whole black gram offering maximum elasticity and rich fermenting qualities for fluffy idlis and dosas.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-PULSE-04',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice Farm, Gwalior, Madhya Pradesh',
      name: 'Giant White Kabuli Chickpeas (Chana)',
      category: 'Pulses & Dals',
      quantity: 130,
      unit: 'kg',
      price: 140,
      description: '12mm giant white garbanzo chickpeas that expand uniformly and cook to buttery tenderness in Amritsari chole.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-PULSE-05',
      farmerId: 'usr-gurpreet-chahal',
      farmerName: 'Gurpreet Chahal',
      farmerEmail: 'gurpreet.chahal@auricvista.farm',
      farmLocation: 'Himalayan Ridge Orchards, Bhaderwah, Jammu & Kashmir',
      name: 'Jammu Chitra Red Rajma (Kidney Beans)',
      category: 'Pulses & Dals',
      quantity: 110,
      unit: 'kg',
      price: 175,
      description: 'Naturally speckled Himalayan chitra kidney beans that soften into a rich velvety curry without disintegrating.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },

    // === HERBS & LEAFY GREENS ===
    {
      id: 'PROD-HERB-01',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic Greenhouses, Kolar, Karnataka',
      name: 'Hydroponic Baby Spinach Leaves (Palak)',
      category: 'Herbs & Leafy Greens',
      quantity: 80,
      unit: 'bunch',
      price: 35,
      description: 'Pesticide-free tender baby palak harvested with roots intact in pure cold mineral water.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-HERB-02',
      farmerId: 'usr-ravi-kumar',
      farmerName: 'Ravi Kumar',
      farmerEmail: 'ravi.kumar@auricvista.farm',
      farmLocation: 'Kumar Organic Red Soil Orchard, Chikkaballapur, Karnataka',
      name: 'Fragrant Country Coriander Leaves (Dhaniya)',
      category: 'Herbs & Leafy Greens',
      quantity: 90,
      unit: 'bunch',
      price: 20,
      description: 'Deep green, intensely fragrant desi dhaniya with tender edible stems harvested at dawn.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1590005354167-6da97870c757?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-HERB-03',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Hosur, Tamil Nadu',
      name: 'Fresh Garden Peppermint (Pudina Leaves)',
      category: 'Herbs & Leafy Greens',
      quantity: 70,
      unit: 'bunch',
      price: 20,
      description: 'Zesty, high-menthol garden mint leaves perfect for cooling chutneys, chai, and refreshing lemonades.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.7,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-HERB-04',
      farmerId: 'usr-venkatesh-rao',
      farmerName: 'Venkatesh Rao',
      farmerEmail: 'venkatesh.rao@auricvista.farm',
      farmLocation: 'Krishna Delta Natural Farm, Tenali, Andhra Pradesh',
      name: 'Organic Fragrant Curry Leaves (Kadi Patta)',
      category: 'Herbs & Leafy Greens',
      quantity: 60,
      unit: 'bunch',
      price: 15,
      description: 'Crisp, dark green aromatic curry leaves picked fresh from old tree groves for quintessential South Indian seasoning.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-HERB-05',
      farmerId: 'usr-suresh-naidu',
      farmerName: 'Suresh Naidu',
      farmerEmail: 'suresh.naidu@auricvista.farm',
      farmLocation: 'Naidu Ancestral Farm, Belagavi, Karnataka',
      name: 'Fresh Tender Fenugreek Greens (Methi Leaves)',
      category: 'Herbs & Leafy Greens',
      quantity: 75,
      unit: 'bunch',
      price: 25,
      description: 'Tender, mildly bitter methi greens harvested young for methi thepla, parathas, and dal.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.6,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-HERB-06',
      farmerId: 'usr-lakshmi-devi',
      farmerName: 'Lakshmi Devi',
      farmerEmail: 'lakshmi.devi@auricvista.farm',
      farmLocation: 'Devi Hydroponic Greenhouses, Kolar, Karnataka',
      name: 'Crisp Hydroponic Butterhead Salad Lettuce',
      category: 'Herbs & Leafy Greens',
      quantity: 50,
      unit: 'bunch',
      price: 45,
      description: 'Sweet, buttery crunchy green lettuce heads with intact living root systems grown under filtered sunlight.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },

    // === ORGANIC & NATURAL PRODUCTS ===
    {
      id: 'PROD-ORG-01',
      farmerId: 'usr-pradip-deshmukh',
      farmerName: 'Pradip Deshmukh',
      farmerEmail: 'pradip.deshmukh@auricvista.farm',
      farmLocation: 'Sahyadri Valley Estate, Kolhapur, Maharashtra',
      name: 'Kolhapur Artisanal Sugarcane Jaggery (Organic Gur)',
      category: 'Organic & Natural',
      quantity: 180,
      unit: 'kg',
      price: 85,
      description: 'Golden-brown chemical-free jaggery blocks prepared in traditional open iron pans with zero sulfur or bleaching agents.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-ORG-02',
      farmerId: 'usr-subhash-mondal',
      farmerName: 'Subhash Mondal',
      farmerEmail: 'subhash.mondal@auricvista.farm',
      farmLocation: 'Mangrove Fringe Reserve, Sundarbans, West Bengal',
      name: 'Sundarbans Wild Mangrove Multi-Floral Raw Honey',
      category: 'Organic & Natural',
      quantity: 90,
      unit: 'piece',
      price: 320,
      description: 'Unprocessed, cold-filtered wild raw honey harvested ethically from Apis dorsata honeycombs with natural pollen.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 10.0,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-ORG-03',
      farmerId: 'usr-kavita-patel',
      farmerName: 'Kavita Patel',
      farmerEmail: 'kavita.patel@auricvista.farm',
      farmLocation: 'Patel Natural Spice & Cold-Press Mill, Junagadh, Gujarat',
      name: 'Cold-Pressed Groundnut Oil (Wood-Pressed Kacchi Ghani)',
      category: 'Organic & Natural',
      quantity: 110,
      unit: 'litre',
      price: 240,
      description: 'Single-origin wood-pressed peanut oil extracted below 40°C preserving natural phytosterols and nutty aroma.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.8,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-ORG-04',
      farmerId: 'usr-mathew-joseph',
      farmerName: 'Mathew Joseph',
      farmerEmail: 'mathew.joseph@auricvista.farm',
      farmLocation: 'Highland Mist Spice Plantation, Alappuzha, Kerala',
      name: 'Extra Virgin Cold-Pressed Coconut Oil (Marachekku)',
      category: 'Organic & Natural',
      quantity: 100,
      unit: 'litre',
      price: 280,
      description: 'Traditional stone-and-wood pressed pure coconut oil from fresh sun-dried copra with zero chemical refining.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1544378730-8b5104b18790?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
    {
      id: 'PROD-ORG-05',
      farmerId: 'usr-ghulam-mir',
      farmerName: 'Ghulam Hassan Mir',
      farmerEmail: 'ghulam.mir@auricvista.farm',
      farmLocation: 'Kashmir Valley Saffron Heritage, Sopore, Kashmir',
      name: 'Kashmiri Snow-White Walnut Kernels (Akhrot Giri)',
      category: 'Organic & Natural',
      quantity: 50,
      unit: 'kg',
      price: 950,
      description: 'Crisp, high-oil Kashmiri walnut halves freshly cracked from thin-shelled mountain trees with rich buttery taste.',
      images: JSON.stringify(['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800']),
      qualityScore: 9.9,
      freshnessLabel: 'Excellent',
    },
  ];

  for (const item of diverseListings) {
    await query(
      `INSERT INTO produce_listings (id, farmer_id, farmer_name, farmer_email, farm_location, name, category, quantity_available, unit, price, harvest_date, description, images, quality_score, freshness_label, status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, CURRENT_DATE, $11, $12, $13, $14, 'Active')
       ON CONFLICT (id) DO UPDATE SET
         farmer_id = EXCLUDED.farmer_id,
         farmer_name = EXCLUDED.farmer_name,
         farmer_email = EXCLUDED.farmer_email,
         farm_location = EXCLUDED.farm_location,
         name = EXCLUDED.name,
         category = EXCLUDED.category,
         quantity_available = EXCLUDED.quantity_available,
         unit = EXCLUDED.unit,
         price = EXCLUDED.price,
         description = EXCLUDED.description,
         images = EXCLUDED.images,
         quality_score = EXCLUDED.quality_score,
         freshness_label = EXCLUDED.freshness_label,
         status = 'Active';`,
      [
        item.id,
        item.farmerId,
        item.farmerName,
        item.farmerEmail,
        item.farmLocation,
        item.name,
        item.category,
        item.quantity,
        item.unit,
        item.price,
        item.description,
        item.images,
        item.qualityScore,
        item.freshnessLabel,
      ]
    );
  }

  console.log(`[Seed] Successfully seeded ${farmers.length} farmers and ${diverseListings.length} distinct produce listings into PostgreSQL!`);
}

// Run immediately when executed directly
seedDiverseMarketplace()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error('[Seed Error]', err);
    process.exit(1);
  });
